services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox:/config
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - "9115:9115"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CHANGEME
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=dhairya137@gmail.com
      - GF_SMTP_PASSWORD=
      - GF_SMTP_FROM_ADDRESS=dhairya137@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Monitoring
      - GF_SMTP_STARTTLS_POLICY=MandatoryStartTLS
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data: