apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-notifications
    receivers:
      - uid: email-notifications
        type: email
        settings:
          addresses: admin@opsynth.cloud
          singleEmail: false
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: email-notifications
    group_by: ['alertname', 'instance']
    repeat_interval: 4h
    routes:
      - receiver: email-notifications
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        matchers:
          - severity =~ "warning|critical"
