apiVersion: 1

groups:
  - orgId: 1
    name: Website Monitoring
    folder: Alerts
    interval: 1m
    rules:
      - uid: website_down
        title: Website Down
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P8E80F9AEF21F6940
            model:
              expr: probe_success == 0
              intervalMs: 30000
              maxDataPoints: 43200
              refId: A
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        dashboardUid: ""
        panelId: 0
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: "Website Down - ${instance}"
          description: |
            Website ${instance} is not responding to HTTP requests
            
            Last Check Time: ${time}
            Duration: ${duration}
            
            Additional Details:
            - HTTP Status: ${probe_http_status_code}
            - SSL Valid: ${probe_ssl_earliest_cert_expiry}
        labels:
          severity: critical
          instance: ${instance}
